export const STORAGE_KEYS = {
  feeling: 'mirrorcle-current-feeling',
  stats: 'mirrorcle-stats',
  preferences: 'mirrorcle-preferences',
  favorites: 'mirrorcle-favorites',
  sessions: 'mirrorcle-sessions',
  theme: 'mirrorcle-theme',
  onboarding: 'mirrorcle-onboarding-completed',
  notifications: 'mirrorcle-notifications',
  focusAreas: 'mirrorcle-focus-areas',
  practiceFrequency: 'mirrorcle-practice-frequency',
  lastMood: 'mirrorcle-last-mood',
  legalAccepted: 'mirrorcle-legal-accepted',
  dailyFocus: 'mirrorcle-daily-focus',
};
